server:
  port: 8090
spring:
  application:
    name: authentication-server

auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: xuecheng.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:xc.keystore
    secret: xuechengkeystore
    alias: xckey
    password: xuecheng